### PR TITLE
Added emacs plugin

### PR DESCRIPTION
**Pull request by raynei86**

### CODE REVIEW

**Review by lerno — COMMENTED** [review]
The types are a bit wrong, please look at the lexer and grammar in /grammar for c3c. And things like $typeof and $typefrom which create a type and occur in the type location should probably be coded as types.

**Comment by lerno** [comment]
Thank you.

**Comment by raynei86** [comment]
Thanks for fixing it up for me,
you missed a quote on [this line](https://github.com/c3lang/editor-plugins/blob/da45d6ba9781f21a679dc7881466caa361e5f84a/emacs/c3-mode.el#L29) BTW

**Comment by lerno** [comment]
Thanks for pointing that out. Should be ok now.

**Pull request merged**
